sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-22 # needed for tests vm
    - android-23
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock 

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    - echo no | npm install -g grunt-cli
    - npm install
    - grunt compile

matrix:
  include:
    - stage: lint
      language: node_js
      os: linux
      node_js: "8"
      script: grunt lint

    - stage: build
      language: android
      os: linux
      env: 
        - Android="28"
      jdk: oraclejdk8
      before_install: nvm install 8.11.3
      script: "grunt ci:build:android"

    - stage: build
      os: osx
      env: 
        - iOS="10.3"
        - Xcode="9.4"
      osx_image: xcode9.4
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_install:
        - pip install --upgrade pip
        - pip install --user --upgrade matplotlib
        - pip install six
        - pod repo update
      script: "grunt ci:build:ios"

    - stage: webpack
      language: android
      os: linux
      env:
        - Android="28"
        - Platform="Android"
      jdk: oraclejdk8
      before_install: nvm install 8.11.3
      script: "grunt ci:webpack:android"
    
    - stage: webpack
      os: osx
      env: 
        - iOS="10.3"
        - Xcode="9.4"
        - Platform="iOS"
      osx_image: xcode9.4
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_install:
        - pip install --upgrade pip
        - pip install --user --upgrade matplotlib
        - pip install six
        - pod repo update
      script: "grunt ci:webpack:ios"

    - stage: test
      language: android
      os: linux
      env: 
        - Android="28"
      jdk: oraclejdk8
      before_install: nvm install 8.11.3
      before_script:
        - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      script: cd demo && tns deploy android --justlaunch  && tns test android --justlaunch && cd ..

    - stage: test
      language: objective-c
      os: osx 
      osx_image: xcode9.4
      xcode_sdk: iphonesimulator9.3
      before_install:
        - pip install --upgrade pip
        - pip install --user --upgrade matplotlib
        - pip install six
        - export LANG=en_US.UTF-8
        - brew update
        - open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID "560575EC-0A13-4BBC-98F0-7698EE99475E"
        - nvm install 8
        - brew install xcproj
        - gem install xcodeproj 
      script: cd demo && tns deploy ios --justlaunch && tns test ios --justlaunch && cd ..
      
    - stage: deploy
      if: branch = release
      language: node_js 
      node_js: "8"
      before_deploy:
          - cd bin/dist
      deploy:
        provider: npm
        email: "peter@tangrasoft.com"
        api_key:
            secure: "LfeD7xO159FRQe9BafQgWcQW5kMLYWiY3bMSiiUXEK9ea7eGUNJkNdjGBKshgFYrV54pl6p8dFAsX8equkVR4u7yiQH6asPcTDJFUm2eMys2eOwagllSvESsjjZ0EKYLnsBl8IbMpNL6+hfZP8vzbQB7+xKyKBswBWy8EbQYNG9XG78x/SChFPPHO6584a0/Fa7wQrNyIUOtq2Nn4XaQVG8PkOz3c4lIDCFKKhZuHoxQvzoCGOzyxJteq20e4LZrtDsv2A1khf0jm+YWym6aL/YgaegrnqMc33jLV4OlT74FN6k3rYwde4P2FczR0hQAXjVfIAOJA7REOBBWS703T4JWsCXIAyL+ODtR0wQvzy52mkzRDnPWqpKZjYkFLHQjmove9fdqyo9U+3GUw+5sooznoExH9zZfbfuWzdIrsF0nQhzCL6o5wmmGXGofqHOxPl/s3MQ5KiAtMQEXPETUvOI8MQcPnpCDEV0vAvUrMnrBGaRkKqEG32H0Y/jl9Dt7pVig7tqv/nKztf/lEgPs8k4AgJG9jM/AsxT43xN4UF+J8/zdRWsXaDMnQ4c/QYPllTw8xll2YoebZEvIMMJJAeGJmEoWl69ciZJVDV8TReETCavMzTOnJ7HoGFCJPEFWvWBrTBSimtNwnx0iPX+rfdNHRduMCdKV02nu4KAw/Oo="
        skip_cleanup: true
        on:
          branch: release
